#!/usr/bin/sh

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         5
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config initial_polarity first_child
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config focused_border_color "#20BBFC"
bspc config normal_border_color "#424242"

bspc config focus_follows_pointer true

bspc config single_monocle true
#bspc config bottom_monocle_padding 839
