#! /bin/sh

script_name=$0
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi 
done

bspc subscribe desktop_focus desktop_layout node_add node_remove node_transfer | while read line;
do
  windows=$(bspc query -N -n .local.tiled | wc -l)
  layout=$(bspc query -T -d | jq -r .layout)
  if [ $windows -gt 1 ] && [ $layout = "monocle" ]
  then
    bspc config focused_border_color '#20A5BA'
  else
    bspc config focused_border_color '#20bbfc'
  fi
done
