#!/bin/sh

#keycode list to stop confusing myself
#105=Control_R
#108=Alt_R
#133=Super_L
#134=Super_R
#37=Control_L
#38=a
#39=s
#40=d
#41=f
#44=j
#45=k
#46=l
#47=semicolon
#50=Shift_L
#62=Shift_R
#64=Alt_L

Alt_L_keycode="64"
Alt_R_keycode="108"
Control_L_keycode="37"
Control_R_keycode="105"
Shift_L_keycode="50"
Shift_R_keycode="62"
Super_L_keycode="133"
Super_R_keycode="134"


a_mod="Control_L"
a_mod_keycode="$Control_L_keycode"
semicolon_mod="Control_R"
semicolon_mod_keycode="$Control_R_keycode"
a_semicolon_mod_lower_case="control"

s_mod="Super_L"
s_mod_keycode="$Super_L_keycode"
l_mod="Super_R"
l_mod_keycode="$Super_R_keycode"
s_l_mod_lower_case="mod4"

d_mod="Alt_L"
d_mod_keycode="$Alt_L_keycode"
k_mod="Alt_R"
k_mod_keycode="$Alt_R_keycode"
d_k_mod_lower_case="mod1"

f_mod="Shift_L"
f_mod_keycode="$Shift_L_keycode"
j_mod="Shift_R"
j_mod_keycode="$Shift_R_keycode"
f_j_mod_lower_case="shift"


xmodmap -e "keycode 38 = $a_mod $a_mod"
xmodmap -e "add $a_semicolon_mod_lower_case = $a_mod"
xset -r 38
xmodmap -e "keycode $a_mod_keycode = a"
xmodmap -e "remove $a_semicolon_mod_lower_case = a"
xset r $a_mod_keycode

xmodmap -e "keycode 47 = $semicolon_mod $semicolon_mod"
xmodmap -e "add $a_semicolon_mod_lower_case = $semicolon_mod"
xset -r 47
xmodmap -e "keycode $semicolon_mod_keycode = semicolon colon"
xmodmap -e "remove $a_semicolon_mod_lower_case = semicolon"
xset r $semicolon_mod_keycode


xmodmap -e "keycode 39 = $s_mod $s_mod"
xmodmap -e "add $s_l_mod_lower_case = $s_mod"
xset -r 39
xmodmap -e "keycode $s_mod_keycode = s"
xmodmap -e "remove $s_l_mod_lower_case = s"
xset r $s_mod_keycode

xmodmap -e "keycode 46 = $l_mod $l_mod"
xmodmap -e "add $s_l_mod_lower_case = $l_mod"
xset -r 46
xmodmap -e "keycode $l_mod_keycode = l"
xmodmap -e "remove $s_l_mod_lower_case = l"
xset r $l_mod_keycode


xmodmap -e "keycode 40 = $d_mod $d_mod"
xmodmap -e "add $d_k_mod_lower_case = $d_mod"
xset -r 40
xmodmap -e "keycode $d_mod_keycode = d"
xmodmap -e "remove $d_k_mod_lower_case = d"
xset r $d_mod_keycode

xmodmap -e "keycode 45 = $k_mod $k_mod"
xmodmap -e "add $d_k_mod_lower_case = $k_mod"
xset -r 45
xmodmap -e "keycode $k_mod_keycode = k"
xmodmap -e "remove $d_k_mod_lower_case = k"
xset r $k_mod_keycode


xmodmap -e "keycode 41 = $f_mod $f_mod"
xmodmap -e "add $f_j_mod_lower_case = $f_mod"
xset -r 41
xmodmap -e "keycode $f_mod_keycode = f"
xmodmap -e "remove $f_j_mod_lower_case = f"
xset r $f_mod_keycode

xmodmap -e "keycode 44 = $j_mod $j_mod"
xmodmap -e "add $f_j_mod_lower_case = $j_mod"
xset -r 44
xmodmap -e "keycode $j_mod_keycode = j"
xmodmap -e "remove $f_j_mod_lower_case = j"
xset r $j_mod_keycode


pkill xcape
xcape -e "$a_mod=a;$semicolon_mod=semicolon;$s_mod=s;$l_mod=l;$d_mod=d;$k_mod=k;$f_mod=f;$j_mod=j"
