#!/bin/sh

#keycode list to stop confusing myself
#105=Control_R
#37=Control_L
#38=a
#39=s
#46=l
#47=semicolon
#50=Shift_L
#62=Shift_R

a_mod="Shift_L"
semicolon_mod="Shift_R"
a_semicolon_mod_lower_case="shift"

s_mod="Control_L"
l_mod="Control_R"
s_l_mod_lower_case="control"

xmodmap -e "keycode 38 = $a_mod $a_mod"
xmodmap -e "add $a_semicolon_mod_lower_case = $a_mod"
xset -r 38
xmodmap -e "keycode 50 = a"
xmodmap -e "remove $a_semicolon_mod_lower_case = a"
xset r 50

xmodmap -e "keycode 47 = $semicolon_mod $semicolon_mod"
xmodmap -e "add $a_semicolon_mod_lower_case = $semicolon_mod"
xset -r 47
xmodmap -e "keycode 62 = semicolon colon"
xmodmap -e "remove $a_semicolon_mod_lower_case = semicolon"
xset r 62

xmodmap -e "keycode 39 = Control_L Control_L"
xmodmap -e "add control = Control_L"
xset -r 39
xmodmap -e "keycode 37 = s"
xmodmap -e "remove control = s"
xset r 37

xmodmap -e "keycode 46 = Control_R Control_R"
xmodmap -e "add control = Control_R"
xset -r 46
xmodmap -e "keycode 105 = l"
xmodmap -e "remove control = l"
xset r 105


pkill xcape
xcape -e "$a_mod=a;$semicolon_mod=semicolon;Control_L=s;Control_R=l"
