#!/bin/sh

desktops=$(bspc query -D --names)
occupied=$(bspc query -D -d .occupied --names)
focused=$(bspc query -D -d .focused --names)
bspwm=""
while read -r line; do
  if [ "$line" == "$focused" ]
  then
    bspwm+="$focused* "
  elif [[ $occupied =~ $line ]]
  then
    bspwm+="$line  "
  fi
done <<< "$desktops"

time=$(date +%I:%M%P)
date=$(date +%d/%m/%Y)
battery=$(acpi)
networks=$(nmcli --fields type,state,connection device)

status="$bspwm

$time
$date

$battery

$networks"

#notify-send "$(echo "$status")"
dunstify --replace=666 -t 3000 "$(echo "$status")"
